numbers = list(map(int, input("Enter numbers separated by space: ").split()))
largest = max(numbers)
smallest = min(numbers)
print("Largest number:", largest)
print("Smallest number:", smallest)
